Add xfce4 compatibility

diff --git a/xinitrc b/xinitrc
--- a/xinitrc
+++ b/xinitrc
@@ -22,15 +22,24 @@ if [ -f "$usermodmap" ]; then
 fi
 
 if [ -d /etc/X11/xinit/xinitrc.d ] ; then
-	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
-		[ -x "$f" ] && . "$f"
-	done
-	unset f
+    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
+        [ -x "$f" ] && . "$f"
+    done
+    unset f
 fi
 
-pamixer --set-mute &
-pamixer --set-volume 50 &
-pamixer --default-source --set-mute &
-pamixer --default-source --set-volume 0 &
+if command -v pamixer; then
+    pamixer --set-mute &
+    pamixer --set-volume 50 &
+    pamixer --default-source --set-mute &
+    pamixer --default-source --set-volume 0 &
+fi
 
-exec i3
+if command -v i3; then
+    exec i3
+elif command -v startxfce4; then
+    exec startxfce4
+else
+    echo "Unable to find a desktop environment" >&2
+    exit 1
+fi
